inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/DoubleNegation:
  EnforcedStyle: allowed_in_returns

Style/YodaCondition:
  Enabled: false
