#!/usr/bin/env ruby
# frozen_string_literal: true

require "protobug_compiler_protos"
require "protobug/compiler"

compiler_registry = Protobug::Registry.new do |registry|
  Google::Protobuf::Compiler.register_plugin_protos(registry)
end

request = Google::Protobuf::Compiler::CodeGeneratorRequest.decode($stdin, registry: compiler_registry)
SimpleCov.command_name "protoc-gen-protobug:#{Digest::SHA256.hexdigest(request.to_json)}" if defined?(SimpleCov)

response = Protobug::Compiler.compile!(request)

$stdout.print response.class.encode(response)
