name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3.0"
          - "3.2.3"
          - "3.1.4"
          - "3.0.5"
          - "truffleruby-23.1.2"
          - "jruby-9.4.2.0"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Run the default task
        run: bin/rake
      - name: Ensure no changes
        run: git diff --exit-code HEAD
