name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3.0"
          - "3.2.3"
          - "3.1.4"
          - "3.0.5"
          - "truffleruby-23.1.2"
          - "jruby-9.4.6.0"
        allow_failures:
          - ruby: "truffleruby-23.1.2"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Set up Ruby
        uses: ruby/setup-ruby@cacc9f1c0b3f4eb8a16a6bb0ed10897b43b9de49 # v1.176.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
      - name: Run the default task
        run: bin/rake
      - name: Ensure no changes
        run: git diff --exit-code HEAD
