name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3.0"
          - "3.2.3"
          - "3.1.4"
          - "3.0.5"
          - "truffleruby-23.1.2"
          - "jruby-9.4.6.0"
        allow_failures:
          - ruby: "truffleruby-23.1.2"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Ruby
        uses: ruby/setup-ruby@161cd54b698f1fb3ea539faab2e036d409550e3c # v1.187.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
      - name: Run the default task
        run: bin/rake
      - name: Ensure no changes
        run: git diff --exit-code HEAD
