name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.3.0"
          - "3.2.3"
          - "3.1.4"
          - "3.0.5"
          - "truffleruby-23.1.2"
          - "jruby-9.4.6.0"
        allow_failures:
          - ruby: "truffleruby-23.1.2"

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Set up Ruby
        uses: ruby/setup-ruby@1198b074305f9356bd56dd4b311757cc0dab2f1c # v1.175.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install Protoc
        uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
      - name: Run the default task
        run: bin/rake
      - name: Ensure no changes
        run: git diff --exit-code HEAD
